services:
  app:
    build:
      context: .
    working_dir: /var/www
    networks:
      - laravel

  web:
    image: nginx:latest
    ports:
      - "81:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
