services:
    app:
        build:
            context: .
        working_dir: /var/www
        volumes:
            - app_storage:/var/www/storage
        networks:
            - laravel
        restart: always # สำคัญมากสำหรับ Production เพื่อให้ service รันตลอดเวลา

    web:
        image: nginx:latest
        ports:
            - "3500:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - app_storage:/var/www/storage:ro
        depends_on:
            - app
        networks:
            - laravel
        restart: always

networks:
    laravel:
        driver: bridge

volumes:
    app_storage:
        # Volume สำหรับเก็บไฟล์ Uploads, Logs, Cache ฯลฯ ของ Laravel
        driver: local # ใช้ Local Driver ซึ่งจะเก็บข้อมูลบน Host Machine
