version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smarttv-app
    working_dir: /var/www/html
    volumes:
      - ./app/storage:/var/www/html/storage
      - ./app/public:/var/www/html/public
    networks:
      - smarttv-net

  web:
    image: nginx:latest
    container_name: smarttv-web
    ports:
      - "3500:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - smarttv-net

networks:
  smarttv-net:
    driver: bridge
